language: ruby
rvm:
  - 2.2.1
addons:
  code_climate:
    repo_token: 49e3b5aad6e24d634e04982ce02ee84ae04e869eed9ae1d4f3577debbaa041ea
notifications:
  email:
    recipients:
      - davidjellesma@gmail.com
      - dan.jellesma@gmail.com
    on_failure: change
    on_success: never